#servers: #default로 읽힘 (전부)
#  - dev.bar.com
#  - foo.bar.com
#
#---
#
#spring.config.activate.on-profile: local #local일 때 읽힘 < 이거 Spring Boot에서만 동작함...
kdt:
  # 들여쓰기로 nested를 알림
  version: "v1.0" # 꼭 value를 쓸 때 한 칸을 띄워야함
  minimum-order-amount: 1
  support-vendors: # 배열은 -로 씀
    - a
    - b
    - c
    - d

  description: |- # 멀티라인 기호 '-' 있으면 마지막 개행 포함 안됨
    line 1 hello world
    line 2 xxxx
    line 3