kdt:
  # 들여쓰기로 nested를 알림
  version: "default-v1.0" # 꼭 value를 쓸 때 한 칸을 띄워야함
  minimum-order-amount: 1
  support-vendors: # 배열은 -로 씀
    - default

  description: |- # 멀티라인 기호 '-' 있으면 마지막 개행 포함 안됨
    default 1 hello world
    default 2 xxxx
    default 3